### ISSUE TITLE
Biomarker.nci_thesaurus_concept_id query

### ISSUE THREAD

**Issue by johnmcampbell13** [NCIP/clinical-trials-search#8]
I am trying to use the API to query by the biomarkers.nci_thesaurus_concept_id field, but I can not get any results to return. Even though used concept_id's that appeared in the json output for other queries. I can query by diseases.nci_thesaurus_concept_id and results are returned.  Here is example of result that has biomarkers, but when I use either of the concept_id's as my query term, no results are returned.

trials: [
{
  nct_id: "NCT01674140",
  biomarkers: [
    {
      hugo_biomarker_code: null,
      synonyms: [
        "ERBB2 Negative"
      ],
      nci_thesaurus_concept_id: "C68749",
      name: "HER2/Neu Negative",
      long_name: "HER2/Neu Negative",
      assay_purpose: "Eligibility Criterion - Inclusion"
    },
    {
      hugo_biomarker_code: null,
      synonyms: [ ],
      nci_thesaurus_concept_id: "C15496",
      name: "Progesterone Receptor Positive",
      long_name: "Progesterone Receptor Positive",
      assay_purpose: "Eligibility Criterion - Inclusion"
    }
  ],
  nci_id: "NCI-2012-01995"
}

**Comment by johnmcampbell13** [comment]
I saw some commits in GitHub between Sept 14 and Sep 29 that mentioned changes to Biomarkers.  One was the name for biomarkers.nci_thesaurus_concept_id was changed from nt_term_identifier. Could this be impacting the API query where I want to retrieve trials based on biomarkers.nci_thesaurus_concept_id ??

**Comment by dkrylovsb** [comment]
@johnmcampbell13 , this is fixed; sorry about the delay. The fix should be in Production hopefully by tomorrow.
